### ISSUE TITLE
Create api/job/submit API that supports Blue

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/science-gateway-middleware#11]
### User facing message
```
{
    id: <uuid>
    user_parameters: {
        <any name:value>
    }
}
```
### Internal implementation
- [x] Patch `templates` with user-provided parameters and copy to cluster job folder (Blue specific for the moment)
    - [x] Get template source / dest URIs from Jobs API (local for the moment)
    - [x] Loop over templates, calling patch function on each one (`patch(template, parameters[])`) and copying to cluster job folder.
 - [x] Copy `scripts` from source to destinations

- No need to copy `inputs` for Blue. `inputs` will refer to simulation input files that are typically of large file size. These will be hosted using cloud storage and an upload mechanism from the web client. Blue does not use input files.

**Comment by masonlr** [comment]
Test `setup` endpoint using `curl` within a shell script:

```shell
#!/bin/sh
curl -u lrmason:password -i -H "Content-Type: application/json" -X POST \
  -d '{"id": "d769843b-6f37-4939-96c7-c382c3e74b46", "templates":[{"source_uri":"./resources/templates/Blue.nml", "destination_path":"project/case/"}] ,"scripts": [ { "source_uri": "./resources/scripts/start_job.sh", "destination_path": "project/case/" } ], "parameters": {"viscosity_properties":{"viscosity_phase_1": "0.09"}}, "inputs": []}' \
  http://localhost:5000/setup
```

**Comment by masonlr** [comment]
The following fragment

```json
"templates":[{"source_uri":"./resources/templates/Blue.nml", "destination_path":"project/case/"}] 
```
means take `./resources/templates/Blue.nml` (for the moment, storage is local to middleware), patch `Blue.nml` and store it temporarily in `./tmp/project/case/Blue.nml`. Then, copy this patched version of `Blue.nml` over to the cluster at `<simulation_root>/project/case/Blue.nml`.

`<simulation_root>` is currently hard coded in `views.py` but will later need to be moved to a configuration file or received as a json field from the web client.

**Comment by sgrieve** [comment]
I've just pushed to a branch (11-job-setup-functionality) the refactored new class to handle patching and the shunting of files onto the cluster.

We still need a way of knowing if a job was a success or not, at present the code returns the stderr and stdout of each script that is executed, but nothing is done with that info.

We also need a better name for this class...

**Comment by masonlr** [comment]
For this story: 

> (i) User has unsaved changes in the UI, then (ii) User clicks "RUN" in the UI

What happens in the middleware?

- [ ] Currently we require a POST to `api/setup/<job-id>` (with the unsaved json job data in the body) in order to trigger the `setup` action.

**Comment by masonlr** [comment]
- [ ] Decide on cluster directory naming mechanism. Calling "RUN" should create a job directory that contains the job id within its name.
