### ISSUE TITLE
Add tests to verify app will run on app service and locally

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/science-gateway-middleware#14]
## Description
We are not currently testing to ensure that our project will run either locally (via `run.sh` and `run.py`) or via the Azure app service (using `web.config` and `ptvs_virtual_env_provy.py`). We probably should.

## Notes
Issue came to light when renaming a source file as part of PR #12, we missed changing an import statement in the `run.py` file used to run the app locally. However, we couldn't find a quick way to add a test. We tried adding an empty test file that imported `run.py`. However, this made the tests hang (presumably because we started a server which blocked the terminal).

**Comment by sgrieve** [comment]
Issue dealt with in PR #23
