### ISSUE TITLE
Python version for testing

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/science-gateway-middleware#19]
In Azure we are using `python 3.4`, though `python 3.6` is mentioned in the deployment readme in the middleware git repository. i.e. we mention that the middleware has been tested with `python 3.6`.

**Comment by masonlr** [comment]
Set python 3.4 in `.travis.yml` and `appveyor.yml`

**Comment by sgrieve** [comment]
I have resolved this issue with a hotfix and, unless Travis support can help me get 3.4.1 installed then this is as resolved as it will get.
