### ISSUE TITLE
Research and test database implementations on Azure

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/science-gateway-middleware#22]
Currently recommend avoiding `flask_marshmallow` and instead recommend using `marshmallow` directly for de/serialisation. This allows us to use the `fields.Nested()` method from `marshmallow`.

- [x] Test SQL on Azure via SQLAlchemy
- [x] Test Flask-SQLAlchemy integration (https://flask-marshmallow.readthedocs.io/en/latest/)
- [x] Discuss benefits of NoSQL via Azure Table storage, Azure Cosmos DB
> Current preference is still to implement SQL via sqlalchemy (despite setbacks with python json serialisation/deserialisation)

**Comment by masonlr** [comment]
Vignette for `Job` and `Parameter` tables using SQLAlchemy declarative mapping. One-to-many structure (i.e. one job can have many parameters).

```python
from sqlalchemy import create_engine
engine = create_engine('sqlite:///:memory:', echo=True)
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

from sqlalchemy import Column, Integer, String

from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship


class Job(Base):
    __tablename__ = 'jobs'
    id = Column(Integer, primary_key=True)
    uuid = Column(String)
    user = Column(String)

class Parameter(Base):
    __tablename__ = 'parameters'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    value = Column(String, nullable=False)
    job_id = Column(Integer, ForeignKey('jobs.id'))
    job = relationship("Job", back_populates="parameters")

Job.parameters = relationship("Parameter", order_by=Parameter.id, back_populates="job")

Base.metadata.create_all(engine)


first = Job(uuid='abc-123', user='lrmason')

first.parameters = [Parameter(name='viscosity_phase_1', value="0.07"), Parameter(name='viscosity_phase_2', value="0.04")]


from sqlalchemy.orm import sessionmaker
Session = sessionmaker()
Session.configure(bind=engine)
session = Session()

session.add(first)
session.commit()

test = session.query(Job).filter_by(uuid='abc-123').one()
test.parameters[0].name
test.parameters[0].value
```

**Comment by masonlr** [comment]
Vignette for nested schema via `marshmallow` (https://marshmallow.readthedocs.io/en/latest/nesting.html#nesting)

```python
import datetime as dt

class User(object):
    def __init__(self, name, email):
        self.name = name
        self.email = email
        self.created_at = dt.datetime.now()
        self.friends = []
        self.employer = None

class Blog(object):
    def __init__(self, title, author):
        self.title = title
        self.author = author  # A User object

from marshmallow import Schema, fields, pprint

class UserSchema(Schema):
    name = fields.String()
    email = fields.Email()
    created_at = fields.DateTime()

class BlogSchema(Schema):
    title = fields.String()
    author = fields.Nested(UserSchema)


user = User(name="Monty", email="monty@python.org")
blog = Blog(title="Something Completely Different", author=user)
result, errors = BlogSchema().dump(blog)
pprint(result)
```

**Comment by masonlr** [comment]
@martintoreilly I will aim to implement a serialiser/deserialiser using marshmallow asap. Please let me know if you come across any better/alternative solutions for this.

**Comment by martintoreilly** [comment]
@masonlr Marshmallow looks like a sound option. I had actually added that to my list of things to look at when we got to evaluating an ORM layer (i.e. SQLAlchemy) but had forgotten about it.

**Comment by masonlr** [comment]
@martintoreilly yes, getting there. One of the better explanation I can find is here (http://justanr.github.io/quotly-building-a-simple-json-api-with-flask-marshmallow-and-sqlalchemy). I'm working on trying to add the JSON parsing code into the marshmallow Schema classes themselves, so that we can separate this logic from the the main app code.

**Comment by masonlr** [comment]
@martintoreilly Creating a database row from JSON data via marshmallow schema seems manageable (a work-in-progress implementation is in d41c08540b3be90addca03cf4d6ac07fc3f65a6e). 

I'm still trying to work out how to update a SQL database row via marshmallow schema and JSON loading (this would be used for the job API "patch" calls). I think the `instance` parameter of `Schema.load()` is the way to do this (https://stackoverflow.com/questions/31891676) but still need to test this locally.

**Comment by masonlr** [comment]
@martintoreilly `instance` seems to be a feature of `marshmallow_sqlalchemy` (https://marshmallow-sqlalchemy.readthedocs.io/). I need to look at moving from raw `marshmallow` to `marshmallow_sqlalchemy` in order to use the `instance` feature.

I previously had issues implementing nested schema in `marshmallow_sqlalchemy` (it was straight forward in raw `marshmallow`), so I also need to address this.

**Comment by masonlr** [comment]
@martintoreilly Fragments for database interaction.

Use first codecell for POST creation method in API.
Use second codecell for PATCH update method in API.

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite://'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# Order matters: Initialize SQLAlchemy before Marshmallow
db = SQLAlchemy(app)
ma = Marshmallow(app)

ma = Marshmallow()

class Job(db.Model):
    id = db.Column(db.String, primary_key=True)
    uuid = db.Column(db.String) # CHECK index on this
    # user = db.Column(db.String)
    parameters = db.relationship("Parameter", back_populates="job")
    # templates = db.relationship("Template", back_populates="job")
    # scripts = db.relationship("Script", back_populates="job")
    # inputs = db.relationship("Input", back_populates="job")

class Parameter(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    value = db.Column(db.String)
    job_id = db.Column(db.Integer, db.ForeignKey('job.id'))
    job = db.relationship("Job", back_populates="parameters")


db.create_all()

class ParameterSchema(ma.ModelSchema):
    class Meta:
        model = Parameter

class JobSchema(ma.ModelSchema):
    class Meta:
        fields = ('id', 'parameters')

    parameters = ma.List(ma.Nested(ParameterSchema))

job_schema = JobSchema()
parameter_schema = ParameterSchema()


# <codecell> Manual creation of job

j1 = Job(id="123")
j1.parameters.append(Parameter(name="test1", value="1.2"))
j1.parameters.append(Parameter(name="test2", value="1.6"))
db.session.add(j1)
db.session.commit()


# <codecell> Test nested JSON deserialisation

j1_db = Job.query.filter_by(id="123").first()
job_schema.dump(j1_db)


# <codecell> check load from JSON and update db, via instance argument to Schema.load()
j2 = job_schema.load({'id': '125', 'parameters':[{'name':'test2', 'value':'bob'},{'name':'test3', 'value':'51'}]}, instance=Job().query.first())
q2 = Job.query.first()
q2.id
q2.parameters[0].value
```

**Comment by martintoreilly** [comment]
Code to turn Job objec tinto JSON

**Comment by martintoreilly** [comment]
Plan is to drop the existing InMemory repository and rely on the SQLAlchemy in-memory DB option. As a result, we'll be simplifying a bunch of things like:
- No longer injecting the repo into the app factory (see notes in source)
- Potentially drop the exists() method of the repo if no used

**Comment by martintoreilly** [comment]
TODO: Add a "sameAs" method on Jobs to guarantee that our tests will pass when comparing a locally created Job and a Job retrieved from the database.

**Comment by martintoreilly** [comment]
Potentially useful info on adding UUID field as ID for SQLAlchemy
https://stackoverflow.com/questions/183042/how-can-i-use-uuids-in-sqlalchemy

**Comment by martintoreilly** [comment]
All SQLAlchemy repository tests passing. Still to do are:
- [ ] Duplicate and amend the Job API test file to test APIs using the SQLAlchemy repo (we can remove the in-memory tests when we have the SQLAlchemy ones passing and solely use SQLAlchemy repos for our app. I'd suggest trying a similar fixture-based approach as we used to inject a session fixture into the repo tests. Maybe copy the whole db/session etc fixtures and add a jobs fixture that takes a session argument? Not sure what this will do to our use of test_client() to call the API endpoint.
- [ ] Amend app.py and factory.py to use the new SQLAlchemy repo

**Comment by masonlr** [comment]
f4152d584a065fc13fa1f151abd5bae30097ca48 is a start on the Job API test file. 

* Reusable jobs fixture is _not_ implemented yet
* Round trip json conversion is working

**Comment by masonlr** [comment]
@martintoreilly Is there any reason that we are still querying from the `Job` object rather than passing `Job` to `_session`?

e.g. at https://github.com/alan-turing-institute/science-gateway-middleware/blob/22-sql-database/middleware/job/sqlalchemy_repository.py#L39 is it safe to replace

```python
Job.query.filter_by(id=job_id).first()
```

with

```python
self._session.query(Job).filter_by(id=job_id).first()
```

**Comment by martintoreilly** [comment]
@masonlr Nope. We should be consistent and I favour explicitly using `_session` as this is what we inject.

**Comment by martintoreilly** [comment]
@masonlr Please can you be strict about fixing all linter errors except the 3 we're ignoring (`401`, `403`, `405`) as these will cause the CI on Travis to fail.

**Comment by masonlr** [comment]
Yes sorry! I was ignoring all local errors from test directory because of the `middleware` argument:

```shell
flake8 middleware/ --ignore=F401,F403,F405`
```

Will get the atom linter working properly :muscle:
