### ISSUE TITLE
Set up testing

### ISSUE THREAD

**Issue by sgrieve** [alan-turing-institute/science-gateway-middleware#3]

**Comment by sgrieve** [comment]
Currently exploring how to mock ssh connections so we can test both ends of the middleware. https://pypi.python.org/pypi/mock-ssh-server/0.2.0 this seems like it integrates well with pytest.

**Comment by sgrieve** [comment]
mock-ssh-server has zero documentation, and I can't get it to work. So I am moving on to other options.

**Comment by masonlr** [comment]
@sgrieve I'm working on the server right now. I'll update you once it's done.

**Comment by masonlr** [comment]
Okay, there is some documentation and a working VM here now (https://github.com/alan-turing-institute/science-gateway-cluster/tree/master/blue/vm).

**Comment by sgrieve** [comment]
Thanks! I'll hopefully get time to look at this by Friday. After that I'm on leave for a week.

Probably my ignorance here but does it matter that there is a password stored in plaintext in that repo?

**Comment by masonlr** [comment]
Okay, for now the intention is that you change the password for each instance you deploy. Have added an extra step of copying a template JSON file and editing the password and DNS strings. Have added notes to the readme. Thanks.

**Comment by sgrieve** [comment]
I think that we have progressed beyond this issue, so I am closing.
