### ISSUE TITLE
Add token-based authentication to middleware

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/science-gateway-middleware#6]

**Comment by sgrieve** [comment]
We need to discuss how authentication will work at both middleware interfaces. @masonlr mentioned on slack that he had configured ssh tokens on azure using ftp, but at present there is no authentication on the API that the front end will access.

I can easily implement simple user/pass authentication on the relevant parts of the API (Delete, Post, Patch, Put) but this will break all of our tests, so I'd like us to agree on a methodology before having make big changes to the tests.

**Comment by sgrieve** [comment]
Questions:

* How will we handle front end users?
* Do we need a middleware user:password db?

**Comment by martintoreilly** [comment]
See issue #26, which covers adding user login, authentication and access control from a front-end perspective. I think we should be using JWT tokens for authentication to the middleware.

**Comment by masonlr** [comment]
Note, the relevant code for loading setting the paramiko private key (to enable communication with the cluster) is in https://github.com/alan-turing-institute/science-gateway-middleware/blob/11-job-setup-functionality/middleware/ssh.py. This code is not currently in master.

```python
        self.client = paramiko.SSHClient()
        # self.client.load_system_host_keys() # disable for Azure deployment
        self.client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

        # for Azure deployment, assume a private RSA key
        # exists within the keys directory
        key_path = os.path.join("keys", "azure")
        k = paramiko.RSAKey.from_private_key_file(key_path)
```
