### ISSUE TITLE
Front end interface with mock backend interface

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/science-gateway-middleware#7]
Implement front-end facing side of middleware interface defined in #5. Implement actual function calls as dummy methods executing entirely within the middleware. This will allow front-end to start integrating to the middleware.

## Implementation
- [x] In-memory job repository to store jobs (will be a completely separate database backed HTTP API eventually). See PR #8.
    - `exists(job_id)`: Returns `True` if job with ID in repo. Otherwise returns `False`
    - `create(job):` If job with same ID exists in repo, do nothing and return `None`. Otherwise, store job and return stored job.
    - `get_by_id(job_id)`: Return job if a job exists in repo with the provided ID. Otherwise, return `None`.
    - `update(job)`: If job with same ID exists in repo, replace with the supplied job and return the updated job. Otherwise do nothing and return `None`.
    - `delete(job_id)`: If job with same ID exists, remove from repo and return deleted job, Otherwise do nothing and return `None`.
- [x] [Flask RESTful](https://flask-restful.readthedocs.io/) Jobs API class to expose CRUD operations on Jobs via HTTP. This should take a jobs repository as a constructor argument (allows use of in-memory repo for this mock iteration and for testing). Split out to issue #13.
- [x] [Flask RESTful](https://flask-restful.readthedocs.io/) `CreateJobFromTemplate` action HTTP API
- [x] [Flask RESTful](https://flask-restful.readthedocs.io/) `SubmitJob` action HTTP API

**Comment by martintoreilly** [comment]
## Job definition JSON
```
{
    id: <uuid>
    scripts: [source_uri: <uri>, destination_path: <string>]
    templates: [source_uri: <uri>, destination_path: <string>]
    parameters: {
        <any name:value>
    }
}
```
## api/job/submit JSON
UI submits **ALL** parameters exposed to user via UI and these are patched in the job definition file.
```
{
    id: <uuid>
    user_parameters: {
        <any name:value>
    }
}
```

**Comment by martintoreilly** [comment]
## Architecture
- Use [Flask RESTful](https://flask-restful.readthedocs.io/) to define APIs on server side
- Use cross-cloud library for Python-based interactions with cloud resources (e.g. [Apache LibCloud](https://libcloud.apache.org),
- Use SSH wrapper for deploying/fetching resources and running commands from clusters (e.g. [Paramiko](http://www.paramiko.org/) or [Fabric](http://www.fabfile.org/)/[Fabric3](https://pypi.python.org/pypi/Fabric3))
- What to use for client-side chunked + resumable uploads/downloads?
  - Could potentially provide [FineUploader](https://fineuploader.com/) Javascript as result of API call to construct an upload / download web component (or even provide full web component)?
  - Could potentially transpile LibCloud Python to Javascipt and provide that from API endpoint (e.g. using [Transcrypt](http://www.transcrypt.org/), [PyJS](http://pyjs.org/), [Jiphy](https://github.com/timothycrosley/jiphy), [Brython](http://www.brython.info/) or [RapydScript](http://www.rapydscript.com/)

**Comment by martintoreilly** [comment]
Moved architecture comments to new issue (#8).

**Comment by martintoreilly** [comment]
Check overlap with work occurring for issue #11 (SubmitJob API for BLUE)

**Comment by masonlr** [comment]
Flask RESTful `CreateJobFromTemplate` action HTTP API is now implemented in `middleware.api.CasesApi.get()`

**Comment by masonlr** [comment]
Flask RESTful SubmitJob action HTTP API is now implement as an `action` in `middleware.api.RunApi.post()`
