### ISSUE TITLE
Provide all configuration as argument to app constructor / factory

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/science-gateway-middleware#9]
This will make the app more testable and is also a good way to handle variables that need to be different in different environments (e.g. different secrets for each developer / Travis CI / staging / production etc). The Flask documentation covers how to load configurations from Python source files and config files, as well as how to have a base config / config inheritance. We should also figure out how we can access the app configuration from the app.test_client() object as this would be useful in testing. However, we can live without it as we can add our test objects to the test config when we create a test app instance and, as they are passed by preference, we can still access them after they are passed to the app constructor / factory.

**Comment by martintoreilly** [comment]
@sgrieve Worth thinking about whether to pick up this ticket as part of your current refactoring to merge me and @masonlr's middleware contributions. Equally happy if we pick this up later once we've a working v0.1 end to end set up working, so totally your call.

**Comment by sgrieve** [comment]
@martintoreilly I have some time this morning so I will look into this in some more detail. At first glance it seems that it will solve a lot of the testing problems I am having with moving local tests to travis.
